### ISSUE TITLE
Generator documentation

### ISSUE THREAD

**Issue by quantum5** [DMOJ/docs#1]
Having to copy an existing generator or peek at `judge.py` every time I write a generator is just... bad.

**Comment by BinAccel** [comment]
@quantum5 the code that deals with generators is now in `problem.py`, rite?

Should the issue be updated?

**Comment by BinAccel** [comment]
Partially addressed with #14, should this be closed?

**Comment by Xyene** [comment]
@kiritofeng it's good we have a demo problem, but ideally we should have a description up on https://docs.dmoj.ca/en/latest/judge/problem_format/
