### ISSUE TITLE
Remove link to a website that is full of ads

### ISSUE THREAD

**Issue by int-y1** [DMOJ/docs#113]
https://github.com/DMOJ/docs/blob/4034f220dae5fed6247fca49afedf402adf0081d/sample_files/local_settings.py#L10-L13

Find or create a better key creator. As shown below, this website is full of ads and is annoying to use.

![Capture](https://user-images.githubusercontent.com/14223529/132784219-617b25d4-d9d9-402a-9290-ddf8de80ed96.png)

**Comment by Riolku** [comment]
You are encouraged to find or create one yourself, or provide an alternative solution for generating keys, such as `openssh`

**Comment by quantum5** [comment]
Probably better to just do `python -c 'from django.core.management.utils import get_random_secret_key;print(get_random_secret_key())'`.
