### ISSUE TITLE
add mine to js and css

### ISSUE THREAD

**Issue by VeroFess** [DMOJ/docs#25]
if site in docker and use nginx proxy , it may cause trouble ... fix it like 

```
location ~ .*\.(js)$ {
	add_header Content-Type application/javascript;
	gzip_static on;
	expires max;
	root /website;
	break;
}

location ~ .*\.(css)$ {
	add_header Content-Type text/css;
	gzip_static on;
	expires max;
	root /website;
	break;
}

location /static {
	gzip_static on;
	expires max;
	root /website;
}
```

**Comment by quantum5** [comment]
This looks like an attempt to fix broken nginx configuration with even more broken configuration.

**Comment by Xyene** [comment]
* The file path regex can be simpler, for example you don't need the group on `(js)`
* `break` is not needed
* Your nginx configuration should be specifying content types without you having to manually do so -- if you have to, then your nginx is broken
