### ISSUE TITLE
How do I integrate DMOJ judge into my website?

### ISSUE THREAD

**Issue by vignesh10** [DMOJ/docs#28]
I have run dmoj-cli and it is working fine. But I don't understand the working of dmoj live judge. I am looking to integrate this into my custom site where I aim to submit the code to the judge and the judge must return the response (whether all the test cases have been passed or not). How can I achieve this?

**Comment by Xyene** [comment]
Without knowing how your site works in any detail, it seems like you want to implement a custom frontend for the judging system (i.e. one different from [DMOJ/site](https://github.com/DMOJ/site), which is the UI as seen on [dmoj.ca](https://dmoj.ca/)).

What you're probably interested in are the networking capabilities of the judge, specifically this might be a good place to start: https://github.com/DMOJ/judge/blob/master/dmoj/packet.py (notice `dmoj-cli` uses [a stubbed out version of the packet manager](https://github.com/DMOJ/judge/blob/master/dmoj/cli.py#L15)).

That should give you a general idea of how DMOJ judges expect to communicate with a server (e.g. your application), but apart from that I'm afraid we can't offer more support in custom implementations of the DMOJ protocol.

Good luck!
