### ISSUE TITLE
Docs review

### ISSUE THREAD

**Issue by WallE256** [DMOJ/docs#6]
As of now, my break has started, so now it's time to update the docs with the changes from the site (like removing support for RabbitMQ), actually finishing the site docs, and rewrite the judge docs as of the judge major changes in structure. Here by I present a nice task list, which I will modify as I have done them:
- [x] Removing RabbitMQ from the site docs.
- [x] Add the running project part.
- [x] Add the `uwsgi` way of running the site.
- [x] Rewrite the judge config docs.
- [x] Rewrite the problem formatting docs.
- [x] Update the problem examples.

More things will come here as time passes.

**Comment by gjigandi** [comment]
Hi.
I successfully installed the judge and now I am trying to install the site.
I am following the steps [here](https://dmoj.readthedocs.io/en/docsreview/site/installation/#installing-the-site), which I believe is the most updated one.

Currently I am stuck on installing and configuring uwsgi. Precisely, in this step here:
> Now, copy `uwsgi-template.ini` to `uwsgi.ini` and edit it. You should at least change the paths to reflect your install.

Where to find `uwsgi-template.ini`?

Thanks.

**Comment by WallE256** [comment]
Hey @gjigandi. Those files are not pushed to the repo as per @quantum5 saying that they are not up to date. However, you can get them from this gist https://gist.github.com/quantum5/8ff744f8f1f83ada27ebb8dc29747d64. If you need more help, feel free to join our Slack server and ask there on the appropriate channel: https://slack.dmoj.ca/.

**Comment by gjigandi** [comment]
Great, thanks for the answer. I will have a look at the files and I will join the Slack for sure.
