### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by TheAvidDev** [DMOJ/docs#76]
Right now, the v1 API is documented [here](https://dmoj.ca/api) and the v2 API is document in this [gist](https://gist.github.com/Ninjaclasher/a3016f46f6174b7f1822f05170fad729).

Some services choose to include the API documentation in their official documentation (such as [Prometheus](https://prometheus.io/docs/prometheus/latest/querying/api/)) but others don't.

What do we want to do for DMOJ? My vote is to include it in the official docs.

**Comment by kiritofeng** [comment]
+1 for including in official documentation, but we should also add that Gist to a DMOJ flatpage in some form (My personal vote would be for https://dmoj.ca/api/v2/, with a link on the v1 page)
